### ISSUE TITLE
No table displayed

### ISSUE THREAD

**Issue by eugenevk** [JoBinsJP/vue3-datatable#18]
In my VueJS 3 project no table is being displayed. I ran the npm install command, but am surprised there appears to be no need to include / import anything in a Vue component to include the datatable.
Please advise!

**Comment by puncoz** [comment]
could you please share your implementation? 

Also, you can follow the example code from [`https://github.com/JoBinsJP/vue3-datatable/tree/master/src/components/Tables](https://github.com/JoBinsJP/vue3-datatable/tree/master/src/components/Tables).
