### ISSUE TITLE
No works for typescript

### ISSUE THREAD

**Issue by jagjerez** [JoBinsJP/vue3-datatable#20]
my project use typescript language and I have a error when I import component inside file that use it.

![image](https://user-images.githubusercontent.com/28759946/150297294-675a871c-85d0-40e2-a594-c3cae96e804d.png)

**Comment by tmgbedu** [comment]
Sorry for the late response, but here is the simple step and example for the typescript setup.

### Step 1: create a new vue-ts project with vite
```bash
yarn create vite vue3-datatable-example --template vue-ts
```

### Step 2: add ` @jobinsjp/vue3-datatable` as dependency
```bash
yarn add @jobinsjp/vue3-datatable
```

### Step 3: and update `App.vue` as 
```vue
<template>
    <DataTable :rows="data"></DataTable>
</template>
<script setup lang="ts">
    import { DataTable } from "@jobinsjp/vue3-datatable"
    import "@jobinsjp/vue3-datatable/dist/style.css"

    const data = [
        {
            "id": 1,
            "first_name": "Misti",
            "last_name": "Strase",
            "email": "mstrase0@instagram.com",
            "gender": "Non-binary",
            "ip_address": "151.38.32.165",
        },
        {
            "id": 2,
            "first_name": "Valentina",
            "last_name": "Bonas",
            "email": "vbonas1@is.gd",
            "gender": "Agender",
            "ip_address": "103.10.225.246",
        },
    ]
</script>
```

Complete example project is hosted here: https://stackblitz.com/edit/vitejs-vite-jykcvb?file=src/App.vue

**Comment by tmgbedu** [comment]
We will be closing this issue as resolved, but if you encounter any further problems related to this issue in the future, please feel free to reopen it.
