### ISSUE TITLE
Any cdn?

### ISSUE THREAD

**Issue by shahriar0247** [JoBinsJP/vue3-datatable#23]
I wanna use with flask as the front end. So anyone has any everlasting cdn?

**Comment by shershen08** [comment]
you can try to use it from here - https://unpkg.com/browse/@jobinsjp/vue3-datatable@1.0.15/dist/

**Comment by shahriar0247** [comment]
thanks man

**Comment by shahriar0247** [comment]
i ment flask as the backend btw, sorry
