### ISSUE TITLE
Provide code for demos on homepage

### ISSUE THREAD

**Issue by letroot** [JoBinsJP/vue3-datatable#33]
Can you provide the source code(s) for the different tables implemented here: https://vue3-datatable.netlify.app/

They would be very helpful as starters.

Thank you.

**Comment by danbopes** [comment]
Ditto. Was quite disappointed after trying to figure out how the pages were rendered.

**Comment by cdanielzt** [comment]
Please, I didn't know how to use it

**Comment by sdezza** [comment]
Same here, doc isn't clear enough

**Comment by tmgbedu** [comment]
`https://github.com/JoBinsJP/vue3-datatable/tree/master/src` This is the directory which is hosted on `https://vue3-datatable.netlify.app/`
